version: "3.6"

services:
    app-oteller:
        build: .
        image: app-oteller:latest
        volumes:
            - ./logs/:/logs/
        ports:
            - 8182:8182
        depends_on:
            - rabbitmq
            - mongodb

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
        volumes:
            - ./resources/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
        healthcheck:
            test: ["CMD", "curl", "-s", "-f", "http://elasticsearch:9200/_cat/health"]
            interval: 3s
            timeout: 3s
            retries: 10
        ports:
            - 9200:9200

    logstash:
        image: docker.elastic.co/logstash/logstash:7.15.0
        volumes:
            - ./resources/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
        depends_on:
            - elasticsearch
        command: ["logstash", "-f", "/usr/share/logstash/pipeline/logstash.conf"]

    filebeat:
        image: docker.elastic.co/beats/filebeat:6.5.1
        depends_on:
            - elasticsearch
        volumes:
            - ./resources/filebeat.yml:/usr/share/filebeat/filebeat.yml
            - ./logs/:/logs/

    kibana:
        image: docker.elastic.co/kibana/kibana:7.15.0
        depends_on:
            - elasticsearch
        healthcheck:
            test: ["CMD", "curl", "-s", "-f", "http://kibana:5601/api/status"]
            interval: 3s
            timeout: 3s
            retries: 50
        ports:
            - 5601:5601
    
    rabbitmq:
        image: rabbitmq:3.9
        ports:
            - "5672:5672"  # AMQP port
            - "15672:15672"  # RabbitMQ management UI port

    mongodb:
        image: mongo:latest
        ports:
            - "27017:27017"
